---
abstract: 'Query the Google services to retrieve the query suggestions'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.034
  perl: 5.008005
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-AutoSuggest
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Encode: 0
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
  URI: 0
  perl: 5.008_005
resources:
  bugtracker: https://github.com/mudler/WWW--Google--AutoSuggest/issues
  homepage: https://github.com/mudler/WWW--Google--AutoSuggest
  repository: https://github.com/mudler/WWW--Google--AutoSuggest.git
version: 0.01
